### ISSUE TITLE
exect trainer = Trainer(dcgan_network, lsgan_losses, sample_size=64, epochs=epochs, device=device) errors:

### ISSUE THREAD

**Issue by CachCheng** [torchgan/torchgan#73]
Traceback (most recent call last):
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/movan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f75df0ba6a0>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by avik-pal** [comment]
This seems to be an error from the tensorboard logging backend. Can you use `os.environ["TENSORBOARD_LOGGING"] = "0"` and see if the error still exists?

**Comment by CachCheng** [comment]
errors still exist, I don't know how to resolve.

**Comment by avik-pal** [comment]
Ok I think I found the problem. If you have `visdom` installed, you will have to start a server manually. Read [this](https://torchgan.readthedocs.io/en/latest/modules/logging.html#backends).
Else just use `os.environ["VISDOM_LOGGING"] = "0"` and it should be fine.
