### ISSUE TITLE
run on the 2080ti RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:116

### ISSUE THREAD

**Issue by xujin1184104394** [torchgan/torchgan#85]
Running example/self-attention GAN error 
Traceback (most recent call last):
  File "/home1/code/test_gan/self-att-GAN/self-attGAN.py", line 121, in <module>
    trainer(dataloader)
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torchgan-0.0.2-py3.6.egg/torchgan/trainer/trainer.py", line 454, in __call__
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torchgan-0.0.2-py3.6.egg/torchgan/trainer/trainer.py", line 416, in train
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torchgan-0.0.2-py3.6.egg/torchgan/trainer/trainer.py", line 343, in train_iter
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torchgan-0.0.2-py3.6.egg/torchgan/losses/loss.py", line 76, in train_ops
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/code/test_gan/self-att-GAN/self-attGAN.py", line 42, in forward
    return self.model(x)
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xujin/anaconda3/lib/python3.6/site-packages/torchgan-0.0.2-py3.6.egg/torchgan/layers/spectralnorm.py", line 73, in forward
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:116

**Comment by avik-pal** [comment]
@xujin1184104394 Could you post the current versions of the Pytorch that you are using. The bug should be fixed on pytorch-1.0.1. See pytorch/pytorch#15709.

**Comment by xujin1184104394** [comment]
Running self-attention GAN error 


> @ xujin1184104394你能发布你正在使用的当前版本的Pytorch吗？应该在pytorch-1.0.1上修复bug。见[pytorch / pytorch＃15709](https://github.com/pytorch/pytorch/issues/15709)。

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.1.post2
>>> 


The version of pytorch I am using is 1.0.1 should be the latest

**Comment by avik-pal** [comment]
Please run the "Introduction to TorchGAN" notebook. This way we can confirm that if the issue is due to any particular op in spectral normalization.
